Fund 7 challenge Translations - English
C3ETH/c3eth.github.io pull request #74
Opened 2021-11-23 03:21 UTC by PardusEidolon

This is here for the English markdown files for all the Fund 7 challenges to be translated into other languages. when these are complete translations on these documents can begin using the English markdown file as a reference for translators.

2021-11-23 03:31 UTC, wolstaeb commented
The **Guiding Questions** section of the **F7: Catalyst Natives COTI: Pay with ADA Plug-in** challenge is missing and needs to be added.

2021-11-23 19:30 UTC, wolstaeb approved these changes

2021-11-29 00:40 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Accelerate Decentralized Identity/campaign-brief.md
> +How to make the auditing process of funded proposals efficient, distributed and transparent?
```suggestion
What solutions can we develop and implement with Atala PRISM and Cardano today to have the most positive impact and open up opportunities for rapid growth of the Cardano network
```

2021-11-29 00:42 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Accelerate Decentralized Identity/campaign-brief.md
> +We draw inspiration from the work of the Trust Over IP Foundation and the principles from 'Patterns of Commoning.' We see the potential for innovation by linking communities with shared interests und
```suggestion
We draw inspiration from the work of the [Trust Over IP Foundation](https://wiki.trustoverip.org/display/HOME/YOMA+Ecosystem+Task+Force) and the principles from 'Patterns of Commoning.' We see the potential for innovation by linking communities with shared interests under these principles.
```

2021-11-29 00:44 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Accelerate Decentralized Identity/campaign-brief.md
> +For example, small producers like a family ranch in Wyoming have no way to get information about the value of their product through these global aggregation and distribution networks. Currently, a so
```suggestion
For example, small producers like a family ranch in Wyoming have no way to get information about the value of their product through these global aggregation and distribution networks. Currently, a solution such as the [BeefChain project](https://beefchain.com/) is supporting small ranchers.
```

2021-11-29 00:44 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Accelerate Decentralized Identity/campaign-brief.md
> +For example, small producers like a family ranch in Wyoming have no way to get information about the value of their product through these global aggregation and distribution networks. Currently, a so
```suggestion
For example, small producers like a family ranch in Wyoming have no way to get information about the value of their product through these global aggregation and distribution networks. Currently, a solution such as the [BeefChain project](https://beefchain.com/) is supporting small ranchers.
```

2021-11-29 00:49 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Catalyst Accelerator and Mentors/campaign-brief.md
> +- Number of mentors and investors that can be onboarded into the ecosystem
```suggestion
- Distribution of programmes across the world to serve different audiences
```

2021-11-29 01:00 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Grow Latin America, Grow Cardano/campaign-brief.md
> +Fund Size: **$500,000 USD paid in Ada**
```suggestion

Fund Size: **$500,000 USD paid in Ada**
```

2021-11-29 01:00 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Global Sustainable Indepependant-SPO's/campaign-brief.md
> +Fund Size: **$100,000 USD paid in Ada**
```suggestion

Fund Size: **$100,000 USD paid in Ada**
```

2021-11-29 01:01 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Catalyst Accelerator and Mentors/campaign-brief.md
> +
```suggestion
```

2021-11-29 01:01 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Mini-Low-Budget Dapps and Integrations/campaign-brief.md
> +Fund Size: **$200,000 USD paid in Ada**
```suggestion

Fund Size: **$200,000 USD paid in Ada**
```

2021-11-29 01:03 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Miscellaneous Challenge/campaign-brief.md
> +Fund Size: **$200,000 USD paid in Ada**
```suggestion

Fund Size: **$200,000 USD paid in Ada**
```

2021-11-29 01:38 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Nation Building Dapps/campaign-brief.md
> +Introduction video:
```suggestion
[Introduction video](https://archive.org/details/Hernando_De_Soto_The_Mystery_Of_Capital_Why_Capitalism_TriumphsIn_The_West_And_Fails_Everywhere_Else)
```

2021-11-29 01:38 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Nation Building Dapps/campaign-brief.md
> +https://archive.org/details/Hernando_De_Soto_The_Mystery_Of_Capital_Why_Capitalism_TriumphsIn_The_West_And_Fails_Everywhere_Else
```suggestion
```

2021-11-29 01:41 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/New SPO Business Opportunities/campaign-brief.md
> +[Campaign page](https://cardano.ideascale.com/a/campaign-home/26246) and [browse ideas](https://cardano.ideascale.com/a/ideas/top/campaign-filter/byids/campaigns/26246/stage/unspecified).
```suggestion
[Campaign page](https://cardano.ideascale.com/a/campaign-home/26245) and [browse ideas](https://cardano.ideascale.com/a/ideas/top/campaign-filter/byids/campaigns/26245/stage/unspecified).
```

2021-11-29 01:42 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/New SPO Business Opportunities/campaign-brief.md
> +Fund Size: **$250,000 USD paid in Ada**
```suggestion

Fund Size: **$250,000 USD paid in Ada**
```

2021-11-29 01:44 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Open Source Developer Ecosystem/campaign-brief.md
> +Fund Size: **$200,000 USD paid in Ada**
```suggestion

Fund Size: **$200,000 USD paid in Ada**
```

2021-11-29 01:45 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Scale-UP Cardano's Community Hubs/campaign-brief.md
> +Fund Size: **$350,000 USD paid in Ada**
```suggestion

Fund Size: **$350,000 USD paid in Ada**
```

2021-11-29 01:48 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Scale-UP Cardano's Community Hubs/campaign-brief.md
> +How do we encourage Local Community Hubs to drive adoption and awareness of Cardano in the next 6 months?
```suggestion
How do we encourage Local Community Hubs to drive adoption and awareness of Cardano in the next 6 months?

![Scale-Up Cardano Community Hubs](https://i.imgur.com/bZQvrLI.jpeg)
```

2021-11-29 01:56 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Scale-UP Cardano's Community Hubs/campaign-brief.md
> +https://imgur.com/a/zK5ralU
```suggestion
```

2021-11-29 01:56 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Scale-UP Cardano's Community Hubs/campaign-brief.md
> +https://imgur.com/a/zK5ralU
```suggestion
```

2021-11-29 02:00 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Seeding Cardano's Grassroots DeFi/campaign-brief.md
> +Fund Size: **$200,000 USD paid in Ada**
```suggestion

Fund Size: **$200,000 USD paid in Ada**
```

2021-11-29 02:01 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Seeding Cardano's Grassroots DeFi/campaign-brief.md
> +https://cointelegraph.com/news/hackers-stole-at-least-600m-in-poly-exploit-across-three-chains
```suggestion
- [Hackers stole at least $600M in Poly exploit across three chains](https://cointelegraph.com/news/hackers-stole-at-least-600m-in-poly-exploit-across-three-chains)
```

2021-11-29 02:02 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Seeding Cardano's Grassroots DeFi/campaign-brief.md
> +https://www.theblockcrypto.com/post/111660/thorchain-suffers-5-million-exploit-developers-have-put-out-a-fix
```suggestion
- [Thorchain suffers $5 million exploit, developers have put out a fix](https://www.theblockcrypto.com/post/111660/thorchain-suffers-5-million-exploit-developers-have-put-out-a-fix)
```

2021-11-29 02:03 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Seeding Cardano's Grassroots DeFi/campaign-brief.md
> +At least 4 new teams deploying DeFi dapps on Cardano in 2022 + Managing to form a community in order to gain competitiveness/susteinability
```suggestion
At least 4 new teams deploying DeFi Dapps on Cardano in 2022 + Managing to form a community in order to gain competitiveness/sustainability
```

2021-11-29 02:07 UTC, wolstaeb commented
Change the folder names so that they are simpler and do not include spaces and punctuation. For example:

```.../catalyst/fund7/challenges/A.I. & SingularityNet a $5T market/campaign-brief.md```

Should be changed to something like:

```.../catalyst/fund7/challenges/ai-singularitynet/campaign-brief.md```

The TOML frontmatter is used to name pages and where they sit in the sites hirrachy. Space and punctuations in file or folder names will just cause grief with tools like hugo or gitlocalize.

2021-11-29 02:09 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Boosting Cardano's DeFi/campaign-brief.md
> +linkTitle: " Boosting Cardano's DeFi"
```suggestion
linkTitle: "Boosting Cardano's DeFi"
```

2021-11-29 02:10 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Boosting Cardano's DeFi/campaign-brief.md
> +[https://cointelegraph.com/news/hackers-stole-at-least-600m-in-poly-exploit-across-three-chains]()
```suggestion
- [Hackers stole at least $600M in Poly exploit across three chains](https://cointelegraph.com/news/hackers-stole-at-least-600m-in-poly-exploit-across-three-chains)
```

2021-11-29 02:11 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Boosting Cardano's DeFi/campaign-brief.md
> +[https://www.theblockcrypto.com/post/111660/thorchain-suffers-5-million-exploit-developers-have-put-out-a-fix]()
```suggestion
[Thorchain suffers $5 million exploit, developers have put out a fix](https://www.theblockcrypto.com/post/111660/thorchain-suffers-5-million-exploit-developers-have-put-out-a-fix)
```

2021-11-29 02:13 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Catalyst - Rapid Funding Mechanisms/campaign-brief.md
> +How can we distribute Cardano Treasury funds more rapidly in a transparent, accountable, and safe manner?
```suggestion
How can we distribute Cardano treasury funds more rapidly in a transparent, accountable, and safe manner?
```

2021-11-29 07:17 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Community Events/campaign-brief.md
> +Fund Size: **$500,000 USD paid in Ada**
```suggestion
Fund Size: **$200,000 USD paid in Ada**
```

2021-11-29 07:19 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Connecting Japan 日本 Community/campaign-brief.md
> +[Campaign page](https://cardano.ideascale.com/a/campaign-home/26234) and [browse ideas](https://cardano.ideascale.com/a/ideas/top/campaign-filter/byids/campaigns/26234/stage/unspecified).
```suggestion
[Campaign page](https://cardano.ideascale.com/a/campaign-home/26238) and [browse ideas](https://cardano.ideascale.com/a/ideas/top/campaign-filter/byids/campaigns/26238/stage/unspecified).
```

2021-11-29 07:21 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Connecting Japan 日本 Community/campaign-brief.md
> +At the moment most of Ideascale & Catalyst operates in english. This creates a barrier for all non-english communities. If solutions from this challenge prove successful in bridging that gap, they ca
```suggestion
At the moment most of Ideascale & Catalyst operates in english. This creates a barrier for all non-english communities. If solutions from this challenge prove successful in bridging that gap, they can function as an example for other communities.

## Possible directions:

- Translating key documentation
- Creating educational content about Cardano & Catalyst in Japanese
- Organising interpreters for Catalyst events
- Organising workshops for new members, CA's, SPO's, proposers
- Setting up community hubs
```

2021-11-29 07:24 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/DApps - Integrations/campaign-brief.md
> +Fund Size: **$250,000 USD paid in Ada**
```suggestion

Fund Size: **$250,000 USD paid in Ada**
```

2021-11-29 07:24 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/DApps - Integrations/campaign-brief.md
> +## Campaign Brief
```suggestion
```

2021-11-29 07:25 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/DApps - Integrations/campaign-brief.md
> +*~ N/A*
```suggestion
```

2021-11-29 07:26 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/DApps - Integrations/campaign-brief.md
> +Fund Size: **$250,000 USD paid in Ada**
```suggestion

Fund Size: **$250,000 USD paid in Ada**
```

2021-11-29 07:27 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/DApps - Integrations/campaign-brief.md
> +### If the application uses tokens:
```suggestion
If the application uses tokens:
```

2021-11-29 07:28 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Disarm Cyber Disinformation Attacks/campaign-brief.md
> +Fund Size: **$100,000 USD paid in Ada**
```suggestion

Fund Size: **$100,000 USD paid in Ada**
```

2021-11-29 07:29 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Disarm Cyber Disinformation Attacks/campaign-brief.md
> +https://www.wsj.com/articles/brands-face-a-new-online-threat-disinformation-attacks-11602187365
```suggestion
- [Brands Face a New Online Threat: Disinformation Attacks](https://www.wsj.com/articles/brands-face-a-new-online-threat-disinformation-attacks-11602187365)
```

2021-11-29 11:44 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Gamers On-Chained/campaign-brief.md
> +Fund Size: **$250,000 USD paid in Ada**
```suggestion

Fund Size: **$250,000 USD paid in Ada**
```

2021-11-29 11:45 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Lobbying for favorable legislation/campaign-brief.md
> +https://www.coindesk.com/policy/2021/09/07/bitcoin-now-legal-tender-in-el-salvador-marking-world-first/
```suggestion
- [Bitcoin Now Legal Tender in El Salvador, Marking World First](https://www.coindesk.com/policy/2021/09/07/bitcoin-now-legal-tender-in-el-salvador-marking-world-first/)
```

2021-11-29 11:46 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Lobbying for favorable legislation/campaign-brief.md
> +https://www.vice.com/en/article/4avpp3/cryptocurrency-lost-big-in-senate-infrastructure-bill-provision-now-what
```suggestion
[Cryptocurrency Lost Big In Senate Infrastructure Bill Provision. Now What?](https://www.vice.com/en/article/4avpp3/cryptocurrency-lost-big-in-senate-infrastructure-bill-provision-now-what)
```

2021-11-29 11:52 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/Scale-UP Cardano's Community Hubs/campaign-brief.md
> +https://imgur.com/a/feXUVDF
```suggestion
```

2021-11-29 11:56 UTC, wolstaeb requested changes
I've corrected or added missing pieces, links, and corrected some of the markdown formating. These changes have been batched.

2021-11-30 08:41 UTC, wolstaeb approved these changes

2021-11-30 08:50 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/accelerate-decentralized-id/campaign-brief.md
> +hide_feedback: true
```suggestion
hide_feedback: true
description: >
What solutions can we develop and implement with Atala PRISM and Cardano today to have the most positive impact and open up opportunities for the rapid growth of the Cardano network?
```

2021-11-30 08:50 UTC, wolstaeb commented on content/en/catalyst/fund7/challenges/accelerate-decentralized-id/campaign-brief.md
> +What solutions can we develop and implement with Atala PRISM and Cardano today to have the most positive impact and open up opportunities for rapid growth of the Cardano network
```suggestion
What solutions can we develop and implement with Atala PRISM and Cardano today to have the most positive impact and open up opportunities for the rapid growth of the Cardano network?
```

2021-11-30 08:56 UTC, PardusEidolon commented on content/en/catalyst/fund7/challenges/A.I. & SingularityNet a $5T market/campaign-brief.md
> +hide_feedback: true
```suggestion
hide_feedback: true
description: >
How can we create a mutually beneficial partnership with SingularityNet and other A.I. developers and researchers?
```

2021-11-30 09:31 UTC, wolstaeb approved these changes

2021-11-30 09:37 UTC, merged